#include "OePhase.h"

/*
static bool _mHasInit;

static const std::string STR_DEFAULT = "DEFAULT";
static std::vector<std::string> DRAW_PHASE_ARRAY;
static std::unordered_map<std::string, int> DRAW_PHASE_MAP;

const std::string& OePhase::GetDefaultPhase()
{
	return STR_DEFAULT;
}

const std::vector<std::string>& OePhase::GetDrawPhaseArray()
{
	return DRAW_PHASE_ARRAY;
}

std::unordered_map<std::string, int>& OePhase::GetDrawPhaseMap()
{
	return DRAW_PHASE_MAP;
}

void OePhase::Init()
{
	if (_mHasInit)
	{
		return;
	}

	DRAW_PHASE_MAP[STR_DEFAULT] = DEFAULT;
	DRAW_PHASE_MAP["STEP1"] = STEP1;
	DRAW_PHASE_MAP["STEP2"] = STEP2;
	DRAW_PHASE_MAP["STEP3"] = STEP3;
	DRAW_PHASE_MAP["STEP4"] = STEP4;
	DRAW_PHASE_MAP["STEP5"] = STEP5;
	DRAW_PHASE_MAP["STEP6"] = STEP6;
	DRAW_PHASE_MAP["STEP7"] = STEP7;
	DRAW_PHASE_MAP["STEP8"] = STEP8;
	DRAW_PHASE_MAP["STEP9"] = STEP9;
	DRAW_PHASE_MAP["WALK"] = WALK; //ORANGE
	DRAW_PHASE_MAP["BOOST"] = BOOST;
	DRAW_PHASE_MAP["MELEE_GROUND"] = MELEE_GROUND;
	DRAW_PHASE_MAP["MELEE_AIR"] = MELEE_AIR;
	DRAW_PHASE_MAP["JUMP"] = JUMP;
	DRAW_PHASE_MAP["ATTACK_GROUND"] = ATTACK_GROUND;
	DRAW_PHASE_MAP["ATTACK_AIR"] = ATTACK_AIR;
	DRAW_PHASE_MAP["DOUBLE_JUMP"] = DOUBLE_JUMP;
	DRAW_PHASE_MAP["SLIDE"] = SLIDE;
	DRAW_PHASE_MAP["FALLING"] = FALLING;
	DRAW_PHASE_MAP["FALLING_SHOOT"] = FALLING_SHOOT;
	DRAW_PHASE_MAP["STUNNED"] = STUNNED;
	DRAW_PHASE_MAP["GROUND_SHOOT"] = GROUND_SHOOT;
	DRAW_PHASE_MAP["JUMP_SHOOT"] = JUMP_SHOOT;
	DRAW_PHASE_MAP["NUDGE"] = NUDGE;
	DRAW_PHASE_MAP["NUDGE_SHOOT"] = NUDGE_SHOOT;
	DRAW_PHASE_MAP["WALK_SHOOT"] = WALK_SHOOT;
	DRAW_PHASE_MAP["DEATH"] = DEATH;
	DRAW_PHASE_MAP["SLIDE_SHOOT"] = SLIDE_SHOOT;
	DRAW_PHASE_MAP["IDLE2"] = IDLE2;
	DRAW_PHASE_MAP["HANG"] = HANG;
	DRAW_PHASE_MAP["HANG_SHOOT"] = HANG_SHOOT;
	DRAW_PHASE_MAP["HANG_V"] = HANG_V;
	DRAW_PHASE_MAP["HANG_V_SHOOT"] = HANG_V_SHOOT;
	DRAW_PHASE_MAP["HANG_V_UP"] = HANG_V_UP;
	DRAW_PHASE_MAP["HANG_V_UP_SHOOT"] = HANG_V_UP_SHOOT;
	DRAW_PHASE_MAP["HANG_V_DOWN"] = HANG_V_DOWN;
	DRAW_PHASE_MAP["HANG_V_DOWN_SHOOT"] = HANG_V_DOWN_SHOOT;
	DRAW_PHASE_MAP["STAND"] = STAND; //MUTE
	DRAW_PHASE_MAP["ATTACK"] = ATTACK;
	DRAW_PHASE_MAP["RUNNING"] = RUNNING;
	DRAW_PHASE_MAP["CLIMBING"] = CLIMBING;
	DRAW_PHASE_MAP["HANGING"] = HANGING;
	DRAW_PHASE_MAP["JUMPING"] = JUMPING;
	DRAW_PHASE_MAP["HITCH"] = HITCH;
	DRAW_PHASE_MAP["AIR_ATTACK"] = AIR_ATTACK;
	DRAW_PHASE_MAP["HANGING_IDLE"] = HANGING_IDLE;
	DRAW_PHASE_MAP["RESPAWN"] = RESPAWN;
	DRAW_PHASE_MAP["WIND_RUN"] = WIND_RUN;

	DRAW_PHASE_MAP["LEFT"] = LEFT;
	DRAW_PHASE_MAP["RIGHT"] = RIGHT;
	DRAW_PHASE_MAP["NEUTRAL"] = NEUTRAL;

	DRAW_PHASE_MAP["CROUCH"] = CROUCH;
	DRAW_PHASE_MAP["ATTACK_STANDING"] = ATTACK_STANDING;
	DRAW_PHASE_MAP["ATTACK_CROUCHING"] = ATTACK_CROUCHING;
	DRAW_PHASE_MAP["ATTACK_AIR_DOWNRIGHT"] = ATTACK_AIR_DOWNRIGHT;
	DRAW_PHASE_MAP["ATTACK_AIR_RIGHT"] = ATTACK_AIR_RIGHT;

	//boss skeleton
	DRAW_PHASE_MAP["ATTACK_PRE_DASH"] = ATTACK_PRE_DASH;
	DRAW_PHASE_MAP["ATTACK_DASH"] = ATTACK_DASH;
	DRAW_PHASE_MAP["ATTACK_BACKSTEP"] = ATTACK_BACKSTEP;
	DRAW_PHASE_MAP["ATTACK_PRE_CROSS_SLASH"] = ATTACK_PRE_CROSS_SLASH;
	DRAW_PHASE_MAP["ATTACK_CROSS_SLASH"] = ATTACK_CROSS_SLASH;
	DRAW_PHASE_MAP["ATTACK_LEAP"] = ATTACK_LEAP;
	DRAW_PHASE_MAP["ATTACK_HOMING_BONE"] = ATTACK_HOMING_BONE;
	DRAW_PHASE_MAP["ATTACK_BOUNCING_BONE"] = ATTACK_BOUNCING_BONE;

	//frog
	DRAW_PHASE_MAP["ATTACK_ACID"] = ATTACK_ACID;
	DRAW_PHASE_MAP["ATTACK_BIG_BUBBLE"] = ATTACK_BIG_BUBBLE;
	DRAW_PHASE_MAP["ATTACK_BIG_HOP"] = ATTACK_BIG_HOP;
	DRAW_PHASE_MAP["ATTACK_ROLL"] = ATTACK_ROLL;
	DRAW_PHASE_MAP["ATTACK_SHORT_HOP"] = ATTACK_SHORT_HOP;
	DRAW_PHASE_MAP["ATTACK_SLAM"] = ATTACK_SLAM;
	DRAW_PHASE_MAP["ATTACK_WALL"] = ATTACK_WALL;
	DRAW_PHASE_MAP["ATTACK_WARP"] = ATTACK_WARP;

	//snake
	DRAW_PHASE_MAP["ATTACK_HORIZONTAL"] = ATTACK_HORIZONTAL;
	DRAW_PHASE_MAP["ATTACK_VERTICAL"] = ATTACK_VERTICAL;

	DRAW_PHASE_MAP["ATTACK_AIR_UPRIGHT"] = ATTACK_AIR_UPRIGHT;
	DRAW_PHASE_MAP["ATTACK_AIR_UP"] = ATTACK_AIR_UP;
	DRAW_PHASE_MAP["ATTACK_AIR_DOWN"] = ATTACK_AIR_DOWN;
	DRAW_PHASE_MAP["ATTACK_STANDING_UP"] = ATTACK_STANDING_UP;
	DRAW_PHASE_MAP["ATTACK_STANDING_UPRIGHT"] = ATTACK_STANDING_UPRIGHT;

	DRAW_PHASE_MAP["FALLING_ALT"] = FALLING_ALT;

	DRAW_PHASE_MAP["ATTACK_STANDING_SUBWEAPON"] = ATTACK_STANDING_SUBWEAPON;

	DRAW_PHASE_MAP["ATTACK_STUN_STATE"] = ATTACK_STUN_STATE;

	DRAW_PHASE_MAP["STEP10"] = STEP10;
	DRAW_PHASE_MAP["STEP11"] = STEP11;
	DRAW_PHASE_MAP["STEP12"] = STEP12;
	DRAW_PHASE_MAP["STEP13"] = STEP13;
	DRAW_PHASE_MAP["STEP14"] = STEP14;
	DRAW_PHASE_MAP["STEP15"] = STEP15;
	DRAW_PHASE_MAP["STEP16"] = STEP16;
	DRAW_PHASE_MAP["STEP17"] = STEP17;
	DRAW_PHASE_MAP["STEP18"] = STEP18;
	DRAW_PHASE_MAP["STEP19"] = STEP19;

	DRAW_PHASE_MAP["ROPE_CLIMB"] = ROPE_CLIMB;
	DRAW_PHASE_MAP["ROPE_ATTACK"] = ROPE_ATTACK;

	DRAW_PHASE_MAP["TAUNT"] = TAUNT;
	DRAW_PHASE_MAP["DODGING"] = DODGING;

	DRAW_PHASE_MAP["MOVE_ATTACK_L_A"] = MOVE_ATTACK_L_A;
	DRAW_PHASE_MAP["MOVE_ATTACK_L_B"] = MOVE_ATTACK_L_B;
	DRAW_PHASE_MAP["MOVE_ATTACK_L_C"] = MOVE_ATTACK_L_C;

	DRAW_PHASE_MAP["MOVE_ATTACK_H_A"] = MOVE_ATTACK_H_A;
	DRAW_PHASE_MAP["MOVE_ATTACK_H_B"] = MOVE_ATTACK_H_B;
	DRAW_PHASE_MAP["MOVE_ATTACK_H_C"] = MOVE_ATTACK_H_C;

	DRAW_PHASE_MAP["MOVE_ATTACK_AIR_L_A"] = MOVE_ATTACK_AIR_L_A;
	DRAW_PHASE_MAP["MOVE_ATTACK_AIR_L_B"] = MOVE_ATTACK_AIR_L_B;
	DRAW_PHASE_MAP["MOVE_ATTACK_AIR_L_C"] = MOVE_ATTACK_AIR_L_C;

	DRAW_PHASE_MAP["MOVE_ATTACK_AIR_H_A"] = MOVE_ATTACK_AIR_H_A;
	DRAW_PHASE_MAP["MOVE_ATTACK_AIR_H_B"] = MOVE_ATTACK_AIR_H_B;
	DRAW_PHASE_MAP["MOVE_ATTACK_AIR_H_C"] = MOVE_ATTACK_AIR_H_C;

	DRAW_PHASE_MAP["MOVE_ATTACK_S1_A"] = MOVE_ATTACK_S1_A;
	DRAW_PHASE_MAP["MOVE_ATTACK_S1_B"] = MOVE_ATTACK_S1_B;
	DRAW_PHASE_MAP["MOVE_ATTACK_S1_C"] = MOVE_ATTACK_S1_C;

	DRAW_PHASE_MAP["MOVE_ATTACK_S2_A"] = MOVE_ATTACK_S2_A;
	DRAW_PHASE_MAP["MOVE_ATTACK_S2_B"] = MOVE_ATTACK_S2_B;
	DRAW_PHASE_MAP["MOVE_ATTACK_S2_C"] = MOVE_ATTACK_S2_C;

	DRAW_PHASE_MAP["MOVE_ATTACK_AIR_S1_A"] = MOVE_ATTACK_AIR_S1_A;
	DRAW_PHASE_MAP["MOVE_ATTACK_AIR_S1_B"] = MOVE_ATTACK_AIR_S1_B;
	DRAW_PHASE_MAP["MOVE_ATTACK_AIR_S1_C"] = MOVE_ATTACK_AIR_S1_C;

	DRAW_PHASE_MAP["MOVE_ATTACK_AIR_S2_A"] = MOVE_ATTACK_AIR_S2_A;
	DRAW_PHASE_MAP["MOVE_ATTACK_AIR_S2_B"] = MOVE_ATTACK_AIR_S2_B;
	DRAW_PHASE_MAP["MOVE_ATTACK_AIR_S2_C"] = MOVE_ATTACK_AIR_S2_C;

	DRAW_PHASE_MAP["MOVE_ATTACK_UP"] = MOVE_ATTACK_UP;
	DRAW_PHASE_MAP["MOVE_ATTACK_SIDE"] = MOVE_ATTACK_SIDE;
	DRAW_PHASE_MAP["MOVE_ATTACK_DOWN"] = MOVE_ATTACK_DOWN;

	DRAW_PHASE_MAP["MOVE_ATTACK_AIR_UP"] = MOVE_ATTACK_AIR_UP;
	DRAW_PHASE_MAP["MOVE_ATTACK_AIR_SIDE"] = MOVE_ATTACK_AIR_SIDE;
	DRAW_PHASE_MAP["MOVE_ATTACK_AIR_DOWN"] = MOVE_ATTACK_AIR_DOWN;

	DRAW_PHASE_MAP["DODGING_AIR"] = DODGING_AIR;

	DRAW_PHASE_MAP["MOVE_ATTACK_SPECIAL_UP"] = MOVE_ATTACK_SPECIAL_UP;
	DRAW_PHASE_MAP["MOVE_ATTACK_SPECIAL_SIDE"] = MOVE_ATTACK_SPECIAL_SIDE;
	DRAW_PHASE_MAP["MOVE_ATTACK_SPECIAL_DOWN"] = MOVE_ATTACK_SPECIAL_DOWN;
	DRAW_PHASE_MAP["MOVE_ATTACK_SPECIAL_NEUTRAL"] = MOVE_ATTACK_SPECIAL_NEUTRAL;

	DRAW_PHASE_MAP["MOVE_ATTACK_SPECIAL_AIR_UP"] = MOVE_ATTACK_SPECIAL_AIR_UP;
	DRAW_PHASE_MAP["MOVE_ATTACK_SPECIAL_AIR_SIDE"] = MOVE_ATTACK_SPECIAL_AIR_SIDE;
	DRAW_PHASE_MAP["MOVE_ATTACK_SPECIAL_AIR_DOWN"] = MOVE_ATTACK_SPECIAL_AIR_DOWN;
	DRAW_PHASE_MAP["MOVE_ATTACK_SPECIAL_AIR_NEUTRAL"] = MOVE_ATTACK_SPECIAL_AIR_NEUTRAL;

	DRAW_PHASE_MAP["MORE_LEFT"] = MORE_LEFT;
	DRAW_PHASE_MAP["MORE_RIGHT"] = MORE_RIGHT;

	DRAW_PHASE_MAP["INTRO"] = INTRO;
	DRAW_PHASE_MAP["INTRO_FREEZE"] = INTRO_FREEZE;

	DRAW_PHASE_MAP["DESPAWN"] = DESPAWN;
	DRAW_PHASE_MAP["DESPAWN_SUPER"] = DESPAWN_SUPER;
	DRAW_PHASE_MAP["DESPAWN_INVULN"] = DESPAWN_INVULN;

	DRAW_PHASE_ARRAY = std::vector<std::string>();
	for (auto it = DRAW_PHASE_MAP.begin(); it != DRAW_PHASE_MAP.end(); it++)
	{
		std::string phaseString = it->first;
		DRAW_PHASE_ARRAY.push_back(phaseString);
	}
	//Note here that the intent is for these to be sorted alphabetically.

	_mHasInit = true;
}
*/