//THIS CODE IS AUTOMATICALLY GENERATED, DO NOT EDIT!

#include "ComponentType.h"

const char* ComponentType_GetComponentName(ComponentType ctype)
{
    switch (ctype)
    {
    case C_CrComBossData:
        return "CrComBossData";
    case C_CrComCameraData:
        return "CrComCameraData";
    case C_CrComChallengeMode:
        return "CrComChallengeMode";
    case C_CrComDoomTimer:
        return "CrComDoomTimer";
    case C_CrComEnemyKitData:
        return "CrComEnemyKitData";
    case C_CrComGameOver:
        return "CrComGameOver";
    case C_CrComIsGameFrozen:
        return "CrComIsGameFrozen";
    case C_CrComIsStarted:
        return "CrComIsStarted";
    case C_CrComPersistence:
        return "CrComPersistence";
    case C_CrComPostBrightness:
        return "CrComPostBrightness";
    case C_CrComResetLevel:
        return "CrComResetLevel";
    case C_CrComSharedData:
        return "CrComSharedData";
    case C_CrComShowLevelName:
        return "CrComShowLevelName";
    case C_CrEffectBloodData:
        return "CrEffectBloodData";
    case C_CrEffectFloodData:
        return "CrEffectFloodData";
    case C_CrEffectWindData:
        return "CrEffectWindData";
    case C_CrModePlayMovieData:
        return "CrModePlayMovieData";
    case C_CrModePressStartMuteData:
        return "CrModePressStartMuteData";
    case C_CrSharedFlameData:
        return "CrSharedFlameData";
    case C_CrTagIsJellyfishShield:
        return "CrTagIsJellyfishShield";
    case C_CrThingEnemyAnchorManData:
        return "CrThingEnemyAnchorManData";
    case C_CrThingEnemyBoneMummyData:
        return "CrThingEnemyBoneMummyData";
    case C_CrThingEnemyCrabData:
        return "CrThingEnemyCrabData";
    case C_CrThingEnemyDeathBallData:
        return "CrThingEnemyDeathBallData";
    case C_CrThingEnemyFastDogData:
        return "CrThingEnemyFastDogData";
    case C_CrThingEnemyFishData:
        return "CrThingEnemyFishData";
    case C_CrThingEnemyHatMummyData:
        return "CrThingEnemyHatMummyData";
    case C_CrThingEnemyHookManData:
        return "CrThingEnemyHookManData";
    case C_CrThingEnemyMagicianData:
        return "CrThingEnemyMagicianData";
    case C_CrThingEnemyNewBossDemonData:
        return "CrThingEnemyNewBossDemonData";
    case C_CrThingEnemyNewBossEyeData:
        return "CrThingEnemyNewBossEyeData";
    case C_CrThingEnemyNewBossFinalData:
        return "CrThingEnemyNewBossFinalData";
    case C_CrThingEnemyNewBossJellyData:
        return "CrThingEnemyNewBossJellyData";
    case C_CrThingEnemyNewBossMonsterData:
        return "CrThingEnemyNewBossMonsterData";
    case C_CrThingEnemyNewBossMonsterTwoData:
        return "CrThingEnemyNewBossMonsterTwoData";
    case C_CrThingEnemyNewBossMothData:
        return "CrThingEnemyNewBossMothData";
    case C_CrThingEnemyNewBossShipData:
        return "CrThingEnemyNewBossShipData";
    case C_CrThingEnemyNewBossShipLaserData:
        return "CrThingEnemyNewBossShipLaserData";
    case C_CrThingEnemyNewBossSquidData:
        return "CrThingEnemyNewBossSquidData";
    case C_CrThingEnemySinewaveData:
        return "CrThingEnemySinewaveData";
    case C_CrThingEnemyStarfishData:
        return "CrThingEnemyStarfishData";
    case C_CrThingObjectAnchorData:
        return "CrThingObjectAnchorData";
    case C_CrThingObjectArrowData:
        return "CrThingObjectArrowData";
    case C_CrThingObjectArrowShooterData:
        return "CrThingObjectArrowShooterData";
    case C_CrThingObjectBubbleData:
        return "CrThingObjectBubbleData";
    case C_CrThingObjectBubbleSpawnerData:
        return "CrThingObjectBubbleSpawnerData";
    case C_CrThingObjectCatStatueData:
        return "CrThingObjectCatStatueData";
    case C_CrThingObjectCoinData:
        return "CrThingObjectCoinData";
    case C_CrThingObjectCrumblePlatformData:
        return "CrThingObjectCrumblePlatformData";
    case C_CrThingObjectDemonData:
        return "CrThingObjectDemonData";
    case C_CrThingObjectDemonHeartData:
        return "CrThingObjectDemonHeartData";
    case C_CrThingObjectEelData:
        return "CrThingObjectEelData";
    case C_CrThingObjectEelSpawnerData:
        return "CrThingObjectEelSpawnerData";
    case C_CrThingObjectEventWindowData:
        return "CrThingObjectEventWindowData";
    case C_CrThingObjectFallingBlockData:
        return "CrThingObjectFallingBlockData";
    case C_CrThingObjectFallingSpikeData:
        return "CrThingObjectFallingSpikeData";
    case C_CrThingObjectFlameData:
        return "CrThingObjectFlameData";
    case C_CrThingObjectFlamethrowerData:
        return "CrThingObjectFlamethrowerData";
    case C_CrThingObjectHookData:
        return "CrThingObjectHookData";
    case C_CrThingObjectJellyColumnData:
        return "CrThingObjectJellyColumnData";
    case C_CrThingObjectKeyButtonData:
        return "CrThingObjectKeyButtonData";
    case C_CrThingObjectKeyDoorData:
        return "CrThingObjectKeyDoorData";
    case C_CrThingObjectMagicianBallData:
        return "CrThingObjectMagicianBallData";
    case C_CrThingObjectMonsterElevatorData:
        return "CrThingObjectMonsterElevatorData";
    case C_CrThingObjectMonsterPlatformData:
        return "CrThingObjectMonsterPlatformData";
    case C_CrThingObjectMovingPlatformData:
        return "CrThingObjectMovingPlatformData";
    case C_CrThingObjectRuinPlatformData:
        return "CrThingObjectRuinPlatformData";
    case C_CrThingObjectSignData:
        return "CrThingObjectSignData";
    case C_CrThingObjectSpikeBallData:
        return "CrThingObjectSpikeBallData";
    case C_CrThingObjectSpikesData:
        return "CrThingObjectSpikesData";
    case C_CrThingObjectSpinnerData:
        return "CrThingObjectSpinnerData";
    case C_CrThingObjectTrainingDummyData:
        return "CrThingObjectTrainingDummyData";
    case C_CrThingObjectWarpData:
        return "CrThingObjectWarpData";
    case C_CrThingPaintingData:
        return "CrThingPaintingData";
    case C_CrThingParticleSpawnerData:
        return "CrThingParticleSpawnerData";
    case C_CrThingPlayerMuteData:
        return "CrThingPlayerMuteData";
    case C_CrThingPlayerMuteMeleeData:
        return "CrThingPlayerMuteMeleeData";
    case C_CrThingTriggerBroadcastData:
        return "CrThingTriggerBroadcastData";
    case C_CrThingTriggerCheckpointData:
        return "CrThingTriggerCheckpointData";
    case C_CrThingTriggerGravityData:
        return "CrThingTriggerGravityData";
    case C_CrThingTriggerLevelCompleteData:
        return "CrThingTriggerLevelCompleteData";
    case C_CrThingTriggerPlaySoundData:
        return "CrThingTriggerPlaySoundData";
    case C_CrThingTriggerSinwaveData:
        return "CrThingTriggerSinwaveData";
    case C_CrWipeCircleData:
        return "CrWipeCircleData";
    case C_CrWipeLinearData:
        return "CrWipeLinearData";
    case C_Body:
        return "Body";
    case C_CollisionEngine:
        return "CollisionEngine";
    case C_BounceData:
        return "BounceData";
    case C_Camera:
        return "Camera";
    case C_CollisionImprintData:
        return "CollisionImprintData";
    case C_DrawActor:
        return "DrawActor";
    case C_FakePosition:
        return "FakePosition";
    case C_FloatyMovementData:
        return "FloatyMovementData";
    case C_FreezeEntityTillOnScreen:
        return "FreezeEntityTillOnScreen";
    case C_GridPosition:
        return "GridPosition";
    case C_IdleCircleData:
        return "IdleCircleData";
    case C_InitialPosition:
        return "InitialPosition";
    case C_LevelDataStub:
        return "LevelDataStub";
    case C_LevelFrameCounter:
        return "LevelFrameCounter";
    case C_Name:
        return "Name";
    case C_Nodes:
        return "Nodes";
    case C_ParentNumber:
        return "ParentNumber";
    case C_PlayerNumber:
        return "PlayerNumber";
    case C_ShakeCamera:
        return "ShakeCamera";
    case C_SpecialMcDeathEffect:
        return "SpecialMcDeathEffect";
    case C_SpecialMcFinalBossEffect:
        return "SpecialMcFinalBossEffect";
    case C_Step:
        return "Step";
    case C_StepCounter:
        return "StepCounter";
    case C_StepTimer:
        return "StepTimer";
    case C_StringSettings:
        return "StringSettings";
    case C_DrawRenderInfo:
        return "DrawRenderInfo";
    case C_DrawStateInfo:
        return "DrawStateInfo";
    case C_ParticleInstance:
        return "ParticleInstance";
    case C_TagIsActor:
        return "TagIsActor";
    case C_TagIsComplete:
        return "TagIsComplete";
    case C_TagIsDrawDisabled:
        return "TagIsDrawDisabled";
    case C_TagIsInPlay:
        return "TagIsInPlay";
    case C_TagIsPlayer:
        return "TagIsPlayer";
    case C_TagIsUpdateDisabled:
        return "TagIsUpdateDisabled";
    case C_MirrorEffect:
        return "MirrorEffect";
    case C_SceneCameraData:
        return "SceneCameraData";
    case C_TagIsIgnoringTransitions:
        return "TagIsIgnoringTransitions";
    case C_TagIsExtraBody:
        return "TagIsExtraBody";
    case C_TagIsEnemy:
        return "TagIsEnemy";
    case C_TagIsBlockingLineOfSight:
        return "TagIsBlockingLineOfSight";
    case C_StunFrames:
        return "StunFrames";
    case C_Random32:
        return "Random32";
    case C_NodeMovingKit:
        return "NodeMovingKit";
    case C_MoveGetter:
        return "MoveGetter";
    case C_Move:
        return "Move";
    case C_IntTag:
        return "IntTag";
    case C_HitFlashKit:
        return "HitFlashKit";
    case C_DrawLineOfSight:
        return "DrawLineOfSight";
    default:
        return "NOT_A_VALID_COMPONENT";
    }
}
