//Defs should be included by including "/engine/utils/Macros.h"

#pragma once

#define GLOBAL_DEF_PARTICLE_LIMIT 4096
#define GLOBAL_DEF_TILE_SIZE 48
#define GLOBAL_DEF_HALF_TILE_SIZE 24
#define GLOBAL_DEF_RECORDING_TOOL_DO_NOT_WRITE_SAVE_FILES
#define GLOBAL_DEF_RECORDING_TOOL_DO_NOT_WRITE_SESSION_DATA
#define GLOBAL_DEF_OVERRIDE_DATE "20240824"
#define GLOBAL_DEF_OVERRIDE_VERSION_NUMBER "1.0.0.1"
#define GLOBAL_DEF_GAME_IS_MUTE_CRIMSON_DX
#define GLOBAL_DEF_REPLAY_BUFFER_SIZE 60 * 5