#pragma once

#if EDITOR

#define CRDEBUG_DEF_BUILT_WITH_DEBUG_DEFS

//#define CRDEBUG_DEF_SHOW_FRAME_COUNT_AND_PLAYER_POSITION
//#define CRDEBUG_DEF_MARK_SAVE_DATA_AS_DEBUG_FLAG_INSTANT_WIN
//#define CRDEBUG_DEF_SIMULATE_DEBUG_FLAG_INSTANT_WIN
//#define CRDEBUG_DEF_UNLOCK_EVERYTHING
//#define CRDEBUG_DEF_SKIP_MOVIES
//#define CRDEBUG_FORCE_COLOR 0

#endif